title: Tanja Andric Memorial Fund
theme: hugo-material-blog
copyright: © 2018 Tanja Andric Memorial Fund
languageCode: en
defaultContentLanguage: en

# Pagination
paginate: 3
paginatePath: page

# Links format
permalinks:
  post: /:year/:month/:title/

params:
  date_format: Mon, 02 Jan 2006 15:04:05 -0700
  description: Tanja Andric Memorial Fund Site
  fundTitle: UIC Tanja Andric Memorial Endowed Scholarship
  donate: give

languages:
  en:
    languageName: English

  # Main menu
    menu:

      main:
        - url: /writings/
          name: Writings
        - url: /eulogies/
          name: Eulogies

      footer1:
        - url: https://www.facebook.com/tandricfund/
          name: Facebook
          weight: 2
        - url: #
          name: Contact Us
          weight: 2

      footer2:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: About
          weight: 2

    params:
      footer_menus:
        - name: Services
          menu: footer2
        - name: Links
          menu: footer1

  sr:
    languageName: Српски
    title: Меморијални фонд Тање Андрић
    copyright: © 2018 Меморијални фонд Тање Андрић

    params:
      footer_menus:
      - name: услуга
        menu: footer2
      - name: линкови
        menu: footer1

    menu:

      main:
      - url: /writings/
        name: Writings
      - url: /eulogies/
        name: Eulogies

      footer1:
      - url: #
        name: услуга 1
        weight: 1
      - url: #
        name: услуга 2
        weight: 2

      footer2:
      - url: /sr/
        name: кући
        weight: 1
      - url: /about/
        name: О томе
        weight: 2


